// Code generated by hertz generator.

package example

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _helloMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querystudentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _personMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querypersondetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addstudentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delstudentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addpersonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delpersonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepersonMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchforpersonreqMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _techMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _selectclassstuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _selectmytechcourseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _selectclassbycourseidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ratescorereqMw() []app.HandlerFunc {
	// your code...
	return nil
}
