// Code generated by hertz generator.

package example

import (
	"context"

	example "classbackend/biz/model/hello/example"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// QueryPersonDetail .
// @router /person/details [GET]
func QueryPersonDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.QueryPersonDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(example.QueryPersonDetailResp)

	c.JSON(consts.StatusOK, resp)
}
