// Code generated by hertz generator.

package example

import (
	example "classbackend/biz/model/hello/example"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SelectMyTechCourse .
// @router /tech/mycourse [GET]
func SelectMyTechCourse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.SelectMyTechCourseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(example.SelectMyTechCourseResp)

	c.JSON(consts.StatusOK, resp)
}

// SelectClassByCourseId .
// @router /tech/queryclass [GET]
func SelectClassByCourseId(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.SelectClassByCourseIdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(example.SelectClassByCourseIdResp)

	c.JSON(consts.StatusOK, resp)
}

// SelectClassStu .
// @router /tech/classstu [GET]
func SelectClassStu(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.SelectClassStuReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(example.SelectClassStuResp)

	c.JSON(consts.StatusOK, resp)
}

// RateScore .
// @router /tech/score [POST]
func RateScore(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.RateScoreReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(example.RateScoreResp)

	c.JSON(consts.StatusOK, resp)
}
